---

# Git settings.
setup_git_repo: true
git_branch: master


# Sentry settings
sentry_dsn: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32353130353566333534393938363235633735313365386339326234376261363635646138653562
          6636656639306637626532663439376663653130613837310a303063313530333566643763366561
          61656439646337636465373835633031373436396262333834336338353366363630353730653166
          3039303832353766320a623237386464326232323766366663346537356333373363623734623230
          39383936646332316639313032313933306436613034373638343661653938313366306132396233
          62376236386239623864656134666261626262343232313535656436646134616237643561306633
          383666393432373334363964366631396232
sentry_organization_slug: ejournal
sentry_project_slug: ejournal


# Database settings.
db_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32353064376338346632663138656231333065366662393236656332353161633332356330643531
          6532396365356665393135353736363030626339653131350a643231336161613739626238656334
          34383034633130636230343532343063303364366234356132363238643537623136346366363634
          3434623433396564340a306332616231363061666136393366356161376365333334653337326435
          6263
db_name: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31353635653031356338333739623038666431323735313937633163643935653134316265363630
          3563313037326264656635613262363862663038323162310a343034373361646661346439616630
          62386163313938346166316536386166633038383432626636326539633965643766623435366337
          3938333034363236340a656665343433376134323163373834376333343130636164363361303839
          6536
db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65633164346338613839363438396666323132313363323939383030376566323161313263646266
          6165613933616262396664386436383764313933323234370a623661656638333035343563393461
          32623265633731623762666365356564353938343535383230633938626639353537303664626631
          3262633436323933370a326638626638363966646335343535313935326636363864353761663532
          38653634626339323361353833366233646236363662623830313432623637343963
db_host: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64613061383736656331326663323665356266653063623134353437316330623231663432333330
          3564363231366465636437353362613839326361376431650a613665396434326636323137343265
          37633731336361346230353035396136393565656538306235343731646338653033383762306537
          3532313363633363340a613336313265366465343134376330366333656638346338623963643834
          3233
db_port: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66373262653463636332636662613764633864643730643938376565643464343466363361366138
          6137653933386439646439613833643930313034383036340a333834663663346639373066663933
          33333866346339386434613430663932653761353866333939613465356434336436656262643534
          6537306231373235660a323232393466626662303336363063353331646336623436326530333233
          3832


# LTI settings.
lti_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65336139353335303833333438636363313235383232386236366335313964613936613131363735
          3633336438323662323138343061323563323964623066620a313562383962663236333733326463
          36306661666539346137336139653435313366396537336431313534616534613738653034616232
          3761616536306632650a363666623632326535623634303534656462633634313066333662343466
          36643763363234643739383736396138616265313437383739386631386130613332636566663663
          66393936383337353764303764653838656335613964346534373563336333363463636439353438
          63373632303032383833653135396531323664373761363836303962363431363736373761393964
          62383465653739383064
lti_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36313766306438386265656436386339396131333239343833386431376430323234343731386662
          3837636265353164633863396262636339663038323163630a633831343132333130363466346463
          65393432323437386437613135613065636532666533373761613334376531313339343433353330
          3461613630373064660a623765643431313034303933663336343635316436313163303230313338
          62303336396562643166386461326365643932383933623336363966373636616463393138366565
          6363336263323833363535313835333864313938623538373765


# Gunicorn settings.
# For the number of workers, a good rule to follow is 2 x number of CPUs + 1
gunicorn_num_workers: "{{ (2 * ansible_processor_cores + 1) }}"

# Setting this to 1 will restart the Gunicorn process each time you make a request, basically reloading the code.
# Very handy when developing. Set to 0 for unlimited requests (default).
gunicorn_max_requests: 0


# RabbitMQ settings.
# TODO Confirm password characters are legal
rabbitmq_server_name: "{{ inventory_hostname }}"
rabbitmq_admin_user: admin
rabbitmq_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38633934343338373761646436633338396265303962613762336238366236383264643938396633
          3138633361373536663338343030323634626433666233310a643336396334356463373730633565
          39643566636331336135626163333036363265303239366233653863626438383039333830616666
          3739353264633234620a666130633361366536383065316537323530623332623830346662633862
          34386337663130666432336332636535363765373937323338366433393139366534616462626331
          3564393337613964653862373365653037633065323666353831
rabbitmq_application_vhost: "{{ application_name }}"
rabbitmq_application_user: "{{ application_name }}"
rabbitmq_application_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63313135313363313063666630623164623364653337626134316330333935373663656632363038
          3561303861383264653733336334303437303362396162310a636562313135346131386231303161
          36313639353762303838383766306264626335326338356665363135356363663565383937633936
          3036616439303561320a616234366538663933396437326365333136643637366430333837346263
          39343134643463373666303031383261373965656364663632653138663230346537326161363464
          37613265323137666532393362653365663065313665356531396235613336313235303038333961
          306139366565353730383064323532323935


# Celery settings.
celery_num_workers: 2


# Application settings.
django_settings_file: "{{ project_name }}.settings.production"
django_secret_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39303834376534623633336437303463663831616563656662373538333231663834333064386238
          3939313639623236333139306562626335306636653765340a353562366438653039366462363161
          31323737386338623465346665323035393166623839663638663138343962373531663437613430
          3231353030646161320a323739383165356565393566613730363935636330643161346262303662
          39363533313437383166383138303430316564376132323262373064363635333432643834633262
          6364383437353335326264656566336331353231663733623034

broker_url: "amqp://{{ rabbitmq_application_user }}:{{ rabbitmq_application_password }}@localhost/{{ rabbitmq_application_vhost }}"

run_django_db_migrations: true
run_django_collectstatic: true


# Nginx settings.
ssl_crt: placeholder
ssl_key: placeholder
csp_frame_ancestors_whitelist: "'self' canvas.uva.nl"
