---

# Virtualenv settings.
enable_deadsnakes_ppa: false
recreate_virtualenv: false
virtualenv_python_version: "{{ base_python_package }}"


# Application settings.
virtualenv_path: "/webapps/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_log_dir: "{{ virtualenv_path }}/logs"
application_django_log_dir: "{{ application_log_dir }}/django"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements/{{ env }}.txt"


# Vuejs static settings.
frontend_web_dir: /var/www/{{ inventory_hostname }}


# Gunicorn settings.
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps


# Nginx settings.
nginx_application_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_application_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ virtualenv_path }}/static"
nginx_media_dir: "{{ virtualenv_path }}/media"


# Django environment variables.
django_environment:
  BASELINK: "{{ baselink }}"
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_NAME: "{{ db_name }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  DATABASE_HOST: "{{ db_host }}"
  DATABASE_PORT: "{{ db_port }}"
  BROKER_URL: "{{ broker_url }}"
  LTI_SECRET: "{{ lti_secret }}"
  LTI_KEY: "{{ lti_key }}"
  EMAIL_HOST: "{{ email_host }}"
  EMAIL_HOST_USER: "{{ email_host_user }}"
  EMAIL_HOST_PASSWORD: "{{ email_host_password }}"
  BACKUP_DIR: "{{ backup_dir }}"
  LOG_DIR: "{{ application_django_log_dir }}"
